title: recept.rymdvarel.se
description: >- # this means to ignore newlines until "baseurl:"
    Yum yum yum! ğŸ•ğŸ”ğŸğŸ—ğŸœğŸŒ®
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recept.rymdvarel.se" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
search_enabled: true
remote_theme: pmarsceill/just-the-docs
