title: recept.rymdvarel.se
logo: "/assets/images/logo.png"
description: "Onaturligt gott ğŸ‘½ğŸ”"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recept.rymdvarel.se" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
search_enabled: true
remote_theme: pmarsceill/just-the-docs
exclude: ['template.md']
permalink: pretty
aux_links:
  "On GitHub":
    - "//github.com/recept-rymdvarel-se/recept-rymdvarel-se.github.io"
plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/apple-icon-96x96.png
